### ISSUE TITLE
Ubuntu 14.04 Software Build Fails

### ISSUE THREAD

**Issue by gorhack** [ApertureLabsLtd/RFIDler#22]
I have already copied the correct file to /etc/udev/rules.d and reloaded the rules. When I attempt to build the file in MPLABX my build fails with the following error. Using a clean install. 

make[2]: *** No rule to make target '/opt/microchip/xc32/v1.33/pic32mx/lib/libmchp_peripheral_32MX795F512L.a', needed by 'dist/debug/production/RFIDler.X.production.hex'.  Stop.

**Comment by AdamLaurie** [comment]
Have you installed the peripheral support libraries as described here?

https://github.com/ApertureLabsLtd/RFIDler#software-build-environment

**Comment by AdamLaurie** [comment]
OK, this was my bad - I had an outdated link pointing to version 1.33 of XC32 instead of 1.34 - now fixed. Please confirm and I'll close this issue. Thanks for reporting it!

**Comment by gorhack** [comment]
Yup, that fixed it! Thanks for the quick reply!!!

On Mon, Jun 22, 2015 at 9:55 AM, Adam Laurie <notifications@github.com>
wrote:

> OK, this was my bad - I had an outdated link pointing to version 1.33 of
> XC32 instead of 1.34 - now fixed. Please confirm and I'll close this issue.
> Thanks for reporting it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ApertureLabsLtd/RFIDler/issues/22#issuecomment-114111801>
> .
>



-- 
Thanks
-Kyle
