### ISSUE TITLE
Include link to udev in README.md

### ISSUE THREAD

**Issue by countrygeek** [ApertureLabsLtd/RFIDler#24]
Hello,
This may be a fairly simple issue, but after twenty minutes of searching and a lot of different leads, I'm unable to locate the simplest thing: the udev rules described in the readme for Linux users.

You should link to the official udev rules and/or just include it in the repo.

Thanks.

**Comment by AdamLaurie** [comment]
I've added a comment to the readme that shows you were it is from outside the IDE (linux-support/71-rfidler-lf-cdc-blacklist.rules). Thanks for bringing this to our attention!
